### ISSUE TITLE
calculation errors on population's end?

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-acs#14]
In the __social__ table: 
for `geoid = 1015100` and `variable=DfHsUS`

+ population PE: 88.1	
+ EDM PE: 12		
+ population PM: 54.7	
+ EDM PM: 4.6

Based on the variable look up
```json
"DfHsUS": [
        "DP02_0080"
    ],
```
pulling pre-calculation data: 
```python
>>> dff = df.loc[df.GEO_ID=='1400000US36061015100', ['DP02_0080E', 'DP02_0080M', 'DP02_0080PE', 'DP02_0080PM']]
>>> dff
      DP02_0080E  DP02_0080M  DP02_0080PE  DP02_0080PM
2283      1000.0       402.0         12.0          4.6
```
In this case, we are taking PE and PM directly from ACS without calculation, so it's a mistake from population? (assuming the variable mapping is correct)

**Comment by EricaMaurer** [comment]
The estimate and margin of error match the database, the percent and percent MOE should be calculated off of DfHs2. Is that what you are using?
