### ISSUE TITLE
demo - AsnEast : for a lot of demographic variables, we are seeing lots of 11.0 for MOE fields. Should we exclude them???

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-acs#16]
e.g.

geoid | GEO_ID | B02015_015M | B02015_017M | B02015_011M | B02015_007M | B02015_012M | B02015_020M
-- | -- | -- | -- | -- | -- | -- | --
2034800 | 1400000US36005034800 | 16.0 | 16.0 | 16.0 | 113.0 | 16.0 | 16.0
2036000 | 1400000US36005036000 | 11.0 | 11.0 | 11.0 | 34.0 | 11.0 | 11.0
2032600 | 1400000US36005032600 | 11.0 | 11.0 | 11.0 | 188.0 | 11.0 | 11.0
2031000 | 1400000US36005031000 | 11.0 | 11.0 | 11.0 | 50.0 | 11.0 | 11.0
2031600 | 1400000US36005031600 | 11.0 | 11.0 | 6.0 | 20.0 | 11.0 | 11.0
2031800 | 1400000US36005031800 | 11.0 | 11.0 | 11.0 | 20.0 | 11.0 | 11.0
2031200 | 1400000US36005031200 | 11.0 | 11.0 | 11.0 | 47.0 | 11.0 | 11.0
2031400 | 1400000US36005031400 | 11.0 | 11.0 | 11.0 | 27.0 | 11.0 | 11.0
2034200 | 1400000US36005034200 | 11.0 | 11.0 | 11.0 | 11.0 | 11.0 | 11.0
2034400 | 1400000US36005034400 | 11.0 | 11.0 | 11.0 | 11.0 | 11.0 | 11.0
2035000 | 1400000US36005035000 | 11.0 | 11.0 | 11.0 | 11.0 | 11.0 | 11.0

If the `11`s are taken into calculation, then we get MOE for BX21 => 251, 
If not, then we get 238, which is closer to what population got (236)

**Comment by SPTKL** [comment]
similar case in __economic__ table
for variable __Pv150t174__, it seems like when calculating MOE, population ignored all M value that are equal to 16. 
e.g. for geoid __1000700__
m_pop: 57
m_mine: 75

data: 
```python
[{'B17024_034M': 16.0,
  'B17024_112M': 16.0,
  'B17024_021M': 16.0,
  'B17024_060M': 57.0,
  'B17024_099M': 16.0,
  'B17024_008M': 16.0,
  'B17024_073M': 16.0,
  'B17024_086M': 16.0,
  'B17024_125M': 16.0,
  'B17024_047M': 16.0}]
```
`sum([i**2 for i in info[0].values() if i != 16])**0.5` ==> 57
`sum([i**2 for i in info[0].values()])**0.5` ==> 75

**Comment by EricaMaurer** [comment]
if the estimate is 0, then MOE should be 0
so the variables used as inputs to this calculation should follow this rule
and then the MOE should match

**Comment by SPTKL** [comment]
Addressed
