### ISSUE TITLE
demo - c,e,m calculated correctly, but not p and z (wrong total?)

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-acs#17]
Since in this case, e and m are correct, we probably picked the wrong group total to calculate p and z against. 
this shows up for both NTA and CT
e.g. `geoid 5032300 variable PopU18F`

p_pop: 40.4	
p_mine: 8.9		
z_pop: 16.1	 
z_mine: 3.6

`PopU18F = B05003_014`
see metadata: https://api.census.gov/data/2017/acs/acs5/groups/B05003.json

B05003_014 => Total!!Female!!Under 18 years
B05003_001 => Group total

**Comment by EricaMaurer** [comment]
percent and percent moe for PopU18F should be calculated off of PopU18_2

**Comment by SPTKL** [comment]
no, we might need to create a logic that finds the total for the given variable.
